language: R
sudo: false
cache: packages
warnings_are_errors: true

before_script:
- Rscript -e "install.packages('devtools')"
- Rscript -e "devtools::install_github('hadley/pkgdown')"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  on:
    branch: master


